name: BlueMapPortalMarkers
version: 0.2.0-SNAPSHOT
main: dev.aldis.bluemapportalmarkers.NetherPortalMarkersPlugin
api-version: '1.21'
author: Max Aldis
description: Adds a toggleable layer of Nether Portal markers to BlueMap, auto-updating as portals are created and discovered.
softdepend: [BlueMap]
